app:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/store
      password: ''
      username: root
server:
  error:
    include-binding-errors: always
    include-message: always